app:
    resource: @AppBundle/Controller/
    type:     annotation
    prefix: /{_locale}/
    requirements:
        _locale: |en|nl|fr|de

#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /{_locale}/group

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"

#simple_things_entity_audit:
#    resource: "@SimpleThingsEntityAuditBundle/Resources/config/routing.yml"
#    prefix: /{_locale}/audit


