# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
imports:
    - { resource: "@AppBundle/Resources/config/services.yml" }

parameters:
    app.twig.asset_exists_extension.class: AppBundle\Twig\Extension\AssetExistsExtension
    app.twig.get_users_extension.class: AppBundle\Twig\Extension\GetUsersExtension

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app_user.registration.form.type:
        class: AppBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    app.twig.asset_exists_extension:
        class: '%app.twig.asset_exists_extension.class%'
        arguments: ['@kernel']
        tags:
            - { name: twig.extension }

    app.twig.get_users_extension:
          class: '%app.twig.get_users_extension.class%'
          arguments:
              doctrine: "@doctrine"
              router: "@router"
          tags:
              - { name: twig.extension }
