services:
    acme_user.registration.form.type:
        class: AppBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: acme_user_registration }
        arguments: [%fos_user.model.user.class%]

    app.default:
        class: AppBundle\Logic\DefaultLogic

    #appbundle.calendar_listener:
    #    class: AppBundle\EventListener\CalendarEventListener
    #    tags:
    #        - { name: kernel.event_listener, event: calendar.load_events, method: loadEvents }
    #    arguments: ['@doctrine.orm.entity_manager']